# Makefile

SOURCE_DIR	:= ./source
INC_DIR		:= ./source
OBJECTS_DIR	:= ./objects
BUILD_DIR	:= ./build

C_FILES		:= $(wildcard $(SOURCE_DIR)/*.c)
C_OBJECTS	:= $(addprefix $(OBJECTS_DIR)/,$(notdir $(C_FILES:.c=.o)))
C_DEPS		:= $(C_OBJECTS:.o=.d)
TARGET		:= $(BUILD_DIR)/Sudoku-Resolver

CFLAGS		:= -MMD -Wall -I$(INC_DIR)
TARGET		:= $(TARGET:=.exe)

ifeq ($(OS),Windows_NT)
	ifeq ($(PROCESSOR_ARCHITEW6432),AMD64)
		CFLAGS += -m64
	else ifeq ($(PROCESSOR_ARCHITEW6432),x86)
		CFLAGS += -m32
	endif
else
    UNAME_S := $(shell uname -s)
    ifeq ($(UNAME_S),Linux)
		UNAME_M := $(shell uname -m)
		ifeq ($(UNAME_M),x86_64)
			CFLAGS += -m64
		else ifeq ($(UNAME_M),x86)
			CFLAGS += -m32
		endif
	endif
endif

# Default
Sudoku-Resolver: $(TARGET)

# Linking object files
$(TARGET): $(C_OBJECTS)
	gcc $(CFLAGS) $(C_OBJECTS) -o $(TARGET)

# Compiling c files
$(OBJECTS_DIR)/%.o: $(SOURCE_DIR)/%.c
	gcc $(CFLAGS) -c $< -o $@

# Include rules of .h dependencies generated by -MMD
-include $(C_DEPS)

# Clean Step
.PHONY: clean
clean:
	rm -f $(OBJECTS_DIR)/*.o $(OBJECTS_DIR)/*.d
